services:
  backend:
    build: ./backend
    container_name: inventory-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://18.205.239.204:8080"
    container_name: inventory-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
